# numpy

In [1]:
#numerical data
#performs arithmetical operations

In [5]:
import numpy as np
l=[10,20,30,40]
an_array=np.array(l)  #an_array is an numpy array
print(an_array)
an_array.shape

[10 20 30 40]


(4,)

In [3]:
import numpy as np
l=[[10,20],[30,40]]
an_array=np.array(l)  #an_array is an numpy array
print(an_array)
an_array.shape
print(an_array[0,1])

[[10 20]
 [30 40]]
20


In [14]:
import numpy as np
l=[10,20,30]
an_array=np.array(l)  #an array is an numpy array
an_array[0]=100
an_array[2]=300
print(an_array)
type(an_array)
an_array.shape

[100  20 300]


(3,)

In [17]:
import numpy as np
# create 2X2 array of zeroes
ex1=np.zeros((4,2),dtype=int)
print(ex1)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [18]:
import numpy as np
# create 2X2 array of 1
ex2=np.ones((4,2),dtype=int)
print(ex2)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [22]:
import numpy as np
# create 4X2 array of 9.0
ex3=np.full((4,2),9)
print(ex3)

[[ 9.  9.]
 [ 9.  9.]
 [ 9.  9.]
 [ 9.  9.]]


/usr/lib/python3/dist-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((4, 2), 9) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [26]:
import numpy as np
# create 2X2 array with diagonal elements 1 and rest 0
ex1=np.eye(4,4)
print(ex1)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [17]:
import numpy as np
# create 2X2 array of array range generates number from 0-3
ex4=np.arange(4)
ex4 = ex4.reshape(2,2)
print(ex4)

[[0 1]
 [2 3]]


In [21]:
import numpy as np
# create 2X2 array of array range generates number from 0-7 with step of 2
ex4=np.arange(0, 8, 2)
ex4 = ex4.reshape(2, 2)
print(ex4)

[[0 2]
 [4 6]]


In [38]:
import numpy as np
l=[10,20,30,40]
an_array=np.array(l)  #an_array is an numpy array
an_array[0]=100
an_array[2]=300
ar=an_array.reshape(2,2)  #reshape our array
print(ar)

[[100  20]
 [300  40]]


# assignment


In [24]:
#slicing of array ~ slice(start, stop, increment(optional))
a = [10, 20, 80,90]
#operation in matrices

TypeError: 'list' object is not callable

In [23]:
#create random number bw 0 to 1
ex5=np.random.randn(4)
print(ex5)

[ 1.94361083  1.06869404  0.409429   -0.71548579]
