In [4]:
import numpy as np


In [12]:
n1 = np.arange(10)
n2 = np.arange(10)
n = n1+ n2

In [13]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
n = np.multiply(n1, n2)
n

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
n = np.sum(n1+n2)
n

90

In [18]:
m = n1.mean()
m

4.5

In [20]:
m1 = np.sqrt(n1)
m1

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [21]:
m2 = np.short(n1) # doubt
m2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [22]:
m3 = np.mean(n1)
m3

4.5

In [30]:
n = np.arange(16)
n = n.reshape(4,4)
m = np.mean(n, axis = 1)
m

array([  1.5,   5.5,   9.5,  13.5])

In [31]:
m1 = np.median(n, axis=0)
m

array([  1.5,   5.5,   9.5,  13.5])

In [32]:
m = np.mean(n, axis = 0)
m

array([ 6.,  7.,  8.,  9.])

In [34]:
#standard deviation ~ doubt
n = np.arange(4)
n = n.reshape(2,2)
m = np.mean(n)
m

1.5

In [39]:
p = [1,2,3,4]
s = [1,2,3,4]
for i in range(0,4):
    p[i] = n[i]-m
    s[i] = p[i]**2
r = np.sum(s[i])*1/4
r

IndexError: index 2 is out of bounds for axis 0 with size 2

In [40]:
# to print unique values of an array

In [18]:
# set operations
s1 = [10,20,30]
s2 = [20,30,40]
x = np.union1d(s1, s2)
y = np.intersect1d(s1, s2)
print(y)
print(x)
z = np.setdiff1d(s1, s2)
print(z) #~ for s1-s2
k=np.in1d(s1,s2)
print(k)
f = np.in1d(s1, s2)


[20 30]
[10 20 30 40]
[10]
[False  True  True]


TypeError: only integer scalar arrays can be converted to a scalar index

In [50]:
# loading files 
f = open("/home/anu/Desktop/anu")
ar = np.loadtxt("/home/anu/Desktop/anu/",',')

NotADirectoryError: [Errno 20] Not a directory: '/home/anu/Desktop/anu/'

In [ ]:
# any, all functions