In [1]:
#using sql in pandas
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split #mostly we are given only one dataset and not test datset... so this library splits test datset from train data randomly
from sklearn import metrics #makes confusion matrix to check accuracy


In [2]:
quality = pd.read_csv('quality.csv')

In [3]:
quality

MemberID  InpatientDays  ERVisits  OfficeVisits  Narcotics  \
0           1              0         0            18          1   
1           2              1         1             6          1   
2           3              0         0             5          3   
3           4              0         1            19          0   
4           5              8         2            19          3   
5           6              2         0             9          2   
6           7             16         1             8          1   
7           8              2         0             8          0   
8           9              2         1             4          3   
9          10              4         2             0          2   
10         11              6         5            20          2   
11         12              0         0             7          4   
12         13              0         1             3          1   
13         14              1         1            20          3   
14         15              6         2            31          3   
15         16              0         0             8          0   
16         17              2         0             9          0   
17         18              3         0            20          1   
18         19              0         0            14          0   
19         20              0         1            20          0   
20         21              5         4            14          1   
21         22              0         1             9          1   
22         23              3         1            12          0   
23         24              8         4             6          2   
24         25              0         0            14          1   
25         26              0         1             7          0   
26         27              3         0            12          0   
27         28              0         2             3          2   
28         29              0         0            18         32   
29         30             13         5            21          6   
..        ...            ...       ...           ...        ...   
101       102              1         2            11          1   
102       103              3         4            14          1   
103       104              0         0            16         10   
104       105              0         0            15         25   
105       106              2         0            28         59   
106       107              0         2            25         20   
107       108              0         0             5         11   
108       109              0         0            12          0   
109       110              0         0             7         21   
110       111              0         1            24          1   
111       112              1         1            29         40   
112       113              2         2            22          0   
113       114              0         0            14         25   
114       115              0         0            12          8   
115       116              0         4            10          1   
116       117              0         0            21         25   
117       118              0         2            16          3   
118       119              0         1            22          9   
119       120              0         0             9          0   
120       121              0         0             9          1   
121       122              0         0             8          0   
122       123              2         0             7          1   
123       124              5         1            17          0   
124       125              0         0            23          0   
125       126              0         0             6          0   
126       127              1         1             5          3   
127       128              1         0             3          2   
128       129             15        11             5

In [4]:
quality.shape

(131, 14)

In [5]:
quality.dtypes

MemberID                  int64
InpatientDays             int64
ERVisits                  int64
OfficeVisits              int64
Narcotics                 int64
DaysSinceLastERVisit    float64
Pain                      int64
TotalVisits               int64
ProviderCount             int64
MedicalClaims             int64
ClaimLines                int64
StartedOnCombination       bool
AcuteDrugGapSmall         int64
PoorCare                  int64
dtype: object

In [6]:
#inpatientdays means days he was admitted

In [7]:
#poorcare is given in int

In [8]:
#this record is of diabetes patient

In [9]:
pd.DataFrame(quality['PoorCare'].value_counts()).T

0   1
PoorCare  98  33

In [10]:
#poorcare is dependent variable

In [11]:
import sys
sys.path


['',
 'C:\\Users\\user\\Anaconda3\\python36.zip',
 'C:\\Users\\user\\Anaconda3\\DLLs',
 'C:\\Users\\user\\Anaconda3\\lib',
 'C:\\Users\\user\\Anaconda3',
 'C:\\Users\\user\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\user\\.ipython']

In [13]:
from pandasql import sqldf

In [14]:
 qualityTrain, qualityTest = train_test_split(quality, test_size = 0.3,random_state = 88)  #.3 means 30% of test data, random state means

In [15]:
#random state is a seed and 88 is a seed and 88 likhne se train aur test ka splitting point same hoga..taki sbka data equal ho

In [16]:
#hum koi b number likh skte hai...bt same hona chaiye

In [17]:
qualityTrain.dtypes

MemberID                  int64
InpatientDays             int64
ERVisits                  int64
OfficeVisits              int64
Narcotics                 int64
DaysSinceLastERVisit    float64
Pain                      int64
TotalVisits               int64
ProviderCount             int64
MedicalClaims             int64
ClaimLines                int64
StartedOnCombination       bool
AcuteDrugGapSmall         int64
PoorCare                  int64
dtype: object

In [18]:
qualityTest.dtypes

MemberID                  int64
InpatientDays             int64
ERVisits                  int64
OfficeVisits              int64
Narcotics                 int64
DaysSinceLastERVisit    float64
Pain                      int64
TotalVisits               int64
ProviderCount             int64
MedicalClaims             int64
ClaimLines                int64
StartedOnCombination       bool
AcuteDrugGapSmall         int64
PoorCare                  int64
dtype: object

In [19]:
qualityTrain

MemberID  InpatientDays  ERVisits  OfficeVisits  Narcotics  \
60         61              0         0             7          0   
111       112              1         1            29         40   
123       124              5         1            17          0   
43         44              4         4            19          1   
57         58              0         0            25         34   
125       126              0         0             6          0   
26         27              3         0            12          0   
9          10              4         2             0          2   
83         84              1         7            26         46   
18         19              0         0            14          0   
103       104              0         0            16         10   
92         93              0         2            15          0   
30         31              5         2             2          0   
55         56             12         7            46          0   
19         20              0         1            20          0   
121       122              0         0             8          0   
93         94              1         0            15          0   
58         59              0         0            19         19   
6           7             16         1             8          1   
81         82              4         5            13          2   
22         23              3         1            12          0   
35         36              0         3            37          2   
117       118              0         2            16          3   
113       114              0         0            14         25   
68         69              0         0             6          0   
27         28              0         2             3          2   
72         73              0         0             1          1   
56         57              8         0            10          0   
49         50              2         0             6          3   
65         66              0         0            25          0   
..        ...            ...       ...           ...        ...   
102       103              3         4            14          1   
78         79              0         0             8          0   
40         41              1         0            15          0   
1           2              1         1             6          1   
77         78              9         4             6          2   
99        100              3         1             7          0   
13         14              1         1            20          3   
29         30             13         5            21          6   
86         87              1         0             7          4   
10         11              6         5            20          2   
70         71              0         5            14          0   
39         40              0         0             8          0   
7           8              2         0             8          0   
89         90              0         1             0          0   
90         91             11         8             9         11   
71         72              5         0            18          1   
4           5              8         2            19          3   
75         76              5         0             7          3   
126       127              1         1             5          3   
34         35              0         8            46          2   
48         49              0         1             2          0   
122       123              2         0             7          1   
108       109              0         0            12          0   
69         70              0         1            13          6   
112       113              2         2            22          0   
97         98              0         7            11          1   
62         63             10         6            20          1   
101       102              1         2            11

In [20]:
qualityTest

MemberID  InpatientDays  ERVisits  OfficeVisits  Narcotics  \
31         32             10         4            45          0   
52         53              0         0            18          0   
64         65              2         0            19          1   
45         46              0         0            21         25   
116       117              0         0            21         25   
110       111              0         1            24          1   
73         74              5         0            14          1   
88         89              0         3             5          3   
15         16              0         0             8          0   
14         15              6         2            31          3   
82         83              0         0            22          9   
124       125              0         0            23          0   
36         37              2         2             9          0   
66         67              0         1             2          1   
33         34              4         2             2          5   
104       105              0         0            15         25   
85         86              0         0             4          0   
17         18              3         0            20          1   
42         43              0         0             0          0   
79         80              0         0             5          0   
127       128              1         0             3          2   
128       129             15        11             5          9   
119       120              0         0             9          0   
98         99              1         1            15          2   
76         77             10         1             3          2   
129       130              0         2            14          1   
24         25              0         0            14          1   
12         13              0         1             3          1   
8           9              2         1             4          3   
74         75              1         3             6          2   
95         96              3         2             5          3   
115       116              0         4            10          1   
91         92              0         0             9          1   
109       110              0         0             7         21   
59         60             12         6            17          2   
100       101              0         0            26          0   
53         54              2         2             7          0   
2           3              0         0             5          3   
20         21              5         4            14          1   
44         45              0         2            13          0   

     DaysSinceLastERVisit  Pain  TotalVisits  ProviderCount  MedicalClaims  \
31             281.958333    32           59             63            133   
52             731.000000     0           18              9             30   
64             731.000000     4           21             23             48   
45             731.000000     1           21              8             34   
116            731.000000     1           21              8             34   
110            581.958333    20           25             42             40   
73             731.000000     9           19             15             34   
88              37.000000     0            8             20             24   
15             731.000000     0            8              5             19   
14             640.958333    70           39             28            101   
82             731.000000    92           22             10             41   
124            731.000000     0           23             34             58   
36              72.000000     4           13             31             50   
66             694.000000     0            3             17            194   
33             196.958333    18            8             24             75   
104      

In [21]:
qualityTrain.shape

(91, 14)

In [22]:
qualityTest.shape

(40, 14)

In [23]:
pd.DataFrame(qualityTrain['PoorCare'].value_counts()).T

0   1
PoorCare  71  20

In [24]:
pd.DataFrame(qualityTest['PoorCare'].value_counts()).T

0   1
PoorCare  27  13

In [25]:
#jiski more probability hoti hai  wo humari baseline prediction hoti hai

In [26]:
import statsmodels.api as sm

In [27]:
QualityLog=sm.Logit.from_formula('PoorCare~OfficeVisits+Narcotics',data=qualityTrain).fit()

Optimization terminated successfully.
         Current function value: 0.412577
         Iterations 6


In [28]:
QualityLog.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               PoorCare   No. Observations:                   91
Model:                          Logit   Df Residuals:                       88
Method:                           MLE   Df Model:                            2
Date:                Thu, 19 Jul 2018   Pseudo R-squ.:                  0.2166
Time:                        18:10:55   Log-Likelihood:                -37.545
converged:                       True   LL-Null:                       -47.923
                                        LLR p-value:                 3.108e-05
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept       -2.7310      0.576     -4.741      0.000      -3.860      -1.602
OfficeVisits     0.0624      0.030      2.064      0.039       0.003       0.122
Narcotics        0.0898      0.033      2.688      0.007       0.024       0.155
================================================================================
"""

In [29]:
QualityLog.fittedvalues

60    -2.294083
111    2.670393
123   -1.669968
43    -1.455359
57     1.882034
125   -2.356495
26    -1.982026
9     -2.551393
83     3.021872
18    -1.857202
103   -0.834524
92    -1.794791
30    -2.606141
55     0.139967
19    -1.482733
121   -2.231672
93    -1.794791
58     0.160781
6     -2.141886
81    -1.740043
22    -1.982026
35    -0.242166
117   -1.463023
113    0.387437
68    -2.356495
27    -2.364158
72    -2.578767
56    -2.106849
49    -2.087138
65    -1.170676
         ...   
102   -1.767417
78    -2.231672
40    -1.794791
1     -2.266709
77    -2.176924
99    -2.294083
13    -1.213377
29    -0.881608
86    -1.934941
10    -1.303162
70    -1.857202
39    -2.231672
7     -2.231672
89    -2.730964
90    -1.181619
71    -1.517771
4     -1.275788
75    -2.024727
126   -2.149550
34     0.319538
48    -2.606141
122   -2.204298
108   -1.982026
69    -1.380901
112   -1.357910
97    -1.954651
62    -1.392948
101   -1.954651
106    0.625036
32    -2.356495
Length: 91, dtype: float

In [30]:
predictTrain=QualityLog.predict()

In [31]:
predictTrain

array([0.09161417, 0.93525685, 0.15842847, 0.18917815, 0.86784455,
       0.08655092, 0.12110308, 0.07233297, 0.95355251, 0.13502946,
       0.30268941, 0.14248635, 0.06874425, 0.53493468, 0.18501494,
       0.0969422 , 0.14248635, 0.54010889, 0.10509187, 0.14930749,
       0.12110308, 0.43975266, 0.18800545, 0.5956655 , 0.08655092,
       0.08594696, 0.07051751, 0.10843295, 0.11035324, 0.2367329 ,
       0.09161417, 0.09936522, 0.6843754 , 0.14248635, 0.09161417,
       0.15182837, 0.36590152, 0.11110785, 0.17979003, 0.15381267,
       0.08655092, 0.1025451 , 0.2229748 , 0.12790462, 0.7799855 ,
       0.1025451 , 0.27220957, 0.98679553, 0.10184198, 0.37125197,
       0.12028977, 0.09627337, 0.19290165, 0.22033058, 0.0969422 ,
       0.17578862, 0.11110785, 0.12028977, 0.25189077, 0.1025451 ,
       0.1262047 , 0.14586386, 0.0969422 , 0.14248635, 0.09391788,
       0.10184198, 0.09161417, 0.22910416, 0.29284462, 0.1262047 ,
       0.21363333, 0.13502946, 0.0969422 , 0.0969422 , 0.06117

In [32]:
#thosse close to 0 are poor care cases

In [33]:
#similarly we can include more variables in model

In [34]:
QualityLog1=sm.Logit.from_formula('PoorCare~InpatientDays+ERVisits+OfficeVisits+Narcotics+DaysSinceLastERVisit+Pain+TotalVisits+ProviderCount+MedicalClaims+ClaimLines+StartedOnCombination+AcuteDrugGapSmall',data=qualityTrain).fit()

Optimization terminated successfully.
         Current function value: 0.311636
         Iterations 26


In [35]:
QualityLog1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               PoorCare   No. Observations:                   91
Model:                          Logit   Df Residuals:                       79
Method:                           MLE   Df Model:                           11
Date:                Thu, 19 Jul 2018   Pseudo R-squ.:                  0.4082
Time:                        18:11:11   Log-Likelihood:                -28.359
converged:                       True   LL-Null:                       -47.923
                                        LLR p-value:                 5.037e-05
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -3.0744      1.517     -2.027      0.043      -6.048      -0.101
StartedOnCombination[T.True]     3.8882      1.517      2.563      0.010       0.914       6.862
InpatientDays                   -0.0041   1.84e+06  -2.21e-09      1.000   -3.61e+06    3.61e+06
ERVisits                         0.0911   1.84e+06   4.95e-08      1.000   -3.61e+06    3.61e+06
OfficeVisits                    -0.0290   1.84e+06  -1.58e-08      1.000   -3.61e+06    3.61e+06
Narcotics                        0.1049      0.053      1.975      0.048       0.001       0.209
DaysSinceLastERVisit            -0.0021      0.002     -1.014      0.310      -0.006       0.002
Pain                            -0.0267      0.025     -1.090      0.276      -0.075       0.021
TotalVisits                      0.0580   1.84e+06   3.15e-08      1.000   -3.61e+06    3.61e+06
ProviderCount                    0.0636      0.039      1.626      0.104      -0.013       0.140
MedicalClaims                   -0.0120      0.027     -0.443      0.658      -0.065       0.041
ClaimLines                      -0.0026      0.009     -0.284      0.777      -0.021       0.016
AcuteDrugGapSmall                0.2074      0.106      1.959      0.050   -7.23e-05       0.415
================================================================================================
"""

In [36]:
QualityLog1.predict()

array([0.0156068 , 0.93548732, 0.06722835, 0.14906053, 0.28438183,
       0.07484959, 0.02614053, 0.15875105, 0.99931423, 0.01828481,
       0.14252325, 0.02922353, 0.18261851, 0.93368246, 0.04158921,
       0.03219174, 0.06975447, 0.61125662, 0.10329112, 0.109957  ,
       0.14003153, 0.1749881 , 0.17854029, 0.78259608, 0.68319958,
       0.08023809, 0.00849411, 0.0745355 , 0.21239558, 0.01844688,
       0.00786506, 0.16303281, 0.69976706, 0.16280609, 0.05885108,
       0.41728026, 0.38493945, 0.03249014, 0.00962092, 0.08843601,
       0.00547801, 0.35435843, 0.05271196, 0.03668766, 0.99979941,
       0.01024583, 0.02998642, 0.99999999, 0.19576209, 0.52222477,
       0.02514855, 0.2166624 , 0.04877863, 0.09056082, 0.02887477,
       0.01670992, 0.03816071, 0.13208767, 0.47559748, 0.01191431,
       0.0303463 , 0.62046612, 0.01528497, 0.4290017 , 0.11189282,
       0.12706604, 0.03662759, 0.03078086, 0.95431685, 0.02453786,
       0.26649559, 0.21108296, 0.27600367, 0.01357578, 0.04014

In [37]:
QualityLog2=sm.Logit.from_formula('PoorCare~InpatientDays+ERVisits+OfficeVisits+Narcotics+DaysSinceLastERVisit+Pain+TotalVisits+ProviderCount+MedicalClaims+ClaimLines+StartedOnCombination+AcuteDrugGapSmall',data=qualityTest).fit()

         Current function value: 0.203811
         Iterations: 35


C:\Users\user\Anaconda3\lib\site-packages\statsmodels\base\model.py:508: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [38]:
QualityLog2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               PoorCare   No. Observations:                   40
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                           11
Date:                Thu, 19 Jul 2018   Pseudo R-squ.:                  0.6768
Time:                        18:11:21   Log-Likelihood:                -8.1524
converged:                      False   LL-Null:                       -25.223
                                        LLR p-value:                 0.0003429
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        1.2291      3.549      0.346      0.729      -5.726       8.184
StartedOnCombination[T.True]    34.4829   6.93e+05   4.98e-05      1.000   -1.36e+06    1.36e+06
InpatientDays                    0.9074   9.66e+05    9.4e-07      1.000   -1.89e+06    1.89e+06
ERVisits                        -2.0275   9.66e+05   -2.1e-06      1.000   -1.89e+06    1.89e+06
OfficeVisits                     0.8687   9.66e+05   8.99e-07      1.000   -1.89e+06    1.89e+06
Narcotics                        1.4158      0.951      1.489      0.136      -0.448       3.279
DaysSinceLastERVisit            -0.0212      0.011     -1.983      0.047      -0.042      -0.000
Pain                            -0.1768      0.109     -1.627      0.104      -0.390       0.036
TotalVisits                     -0.2514   9.66e+05   -2.6e-07      1.000   -1.89e+06    1.89e+06
ProviderCount                   -0.1407      0.117     -1.199      0.230      -0.371       0.089
MedicalClaims                    0.1403      0.093      1.514      0.130      -0.041       0.322
ClaimLines                      -0.0446      0.030     -1.488      0.137      -0.103       0.014
AcuteDrugGapSmall                1.6692      0.887      1.881      0.060      -0.070       3.408
================================================================================================

Possibly complete quasi-separation: A fraction 0.38 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [39]:
QualityLog2.predict()

array([2.47172052e-01, 2.10311816e-01, 1.07330700e-01, 1.00000000e+00,
       1.00000000e+00, 2.87243822e-01, 1.62490313e-01, 1.11860068e-01,
       7.66275186e-05, 1.08407941e-01, 9.69120488e-01, 9.49082974e-01,
       3.27541216e-03, 6.53519578e-03, 4.38453115e-01, 1.00000000e+00,
       3.46554275e-07, 9.65263458e-01, 1.82878302e-08, 1.95538252e-06,
       3.09327626e-06, 1.19287516e-12, 7.75340701e-03, 9.99538790e-01,
       7.71818416e-03, 2.42804661e-01, 8.31518402e-02, 3.71046650e-06,
       4.10295254e-01, 5.90707611e-02, 4.98673296e-07, 1.66970737e-08,
       7.87638893e-06, 1.00000000e+00, 5.96415866e-01, 2.10662233e-01,
       4.05941684e-02, 4.54458932e-03, 1.00000000e+00, 7.70808749e-01])

# LOGISTIC

In [40]:
quality.head()

MemberID  InpatientDays  ERVisits  OfficeVisits  Narcotics  \
0         1              0         0            18          1   
1         2              1         1             6          1   
2         3              0         0             5          3   
3         4              0         1            19          0   
4         5              8         2            19          3   

   DaysSinceLastERVisit  Pain  TotalVisits  ProviderCount  MedicalClaims  \
0                 731.0    10           18             21             93   
1                 411.0     0            8             27             19   
2                 731.0    10            5             16             27   
3                 158.0    34           20             14             59   
4                 449.0    10           29             24             51   

   ClaimLines  StartedOnCombination  AcuteDrugGapSmall  PoorCare  
0         222                 False                  0         0  
1         115                 False                  1         0  
2         148                 False                  5         0  
3         242                 False                  0         0  
4         204                 False                  0         0

In [42]:
quality.shape

(131, 14)

In [44]:
quality.describe()

MemberID  InpatientDays    ERVisits  OfficeVisits   Narcotics  \
count  131.000000     131.000000  131.000000    131.000000  131.000000   
mean    66.000000       2.717557    1.496183     13.229008    4.572519   
std     37.960506       5.099434    2.167501      9.077076    9.713615   
min      1.000000       0.000000    0.000000      0.000000    0.000000   
25%     33.500000       0.000000    0.000000      7.000000    0.000000   
50%     66.000000       0.000000    1.000000     12.000000    1.000000   
75%     98.500000       3.000000    2.000000     18.500000    3.000000   
max    131.000000      30.000000   11.000000     46.000000   59.000000   

       DaysSinceLastERVisit        Pain  TotalVisits  ProviderCount  \
count            131.000000  131.000000   131.000000     131.000000   
mean             480.567112   15.557252    17.442748      23.984733   
std              274.767240   20.418001    12.298318      13.670285   
min                6.000000    0.000000     0.000000       5.000000   
25%              206.958333    1.000000     8.000000      15.000000   
50%              640.958333    8.000000    15.000000      20.000000   
75%              731.000000   23.000000    22.500000      30.000000   
max              731.000000  104.000000    69.000000      82.000000   

       MedicalClaims  ClaimLines  AcuteDrugGapSmall    PoorCare  
count     131.000000  131.000000         131.000000  131.000000  
mean       43.244275  142.862595           2.694656    0.251908  
std        28.886540   91.629921           6.983379    0.435775  
min        11.000000   20.000000           0.000000    0.000000  
25%        25.500000   83.500000           0.000000    0.000000  
50%        37.000000  120.000000           1.000000    0.000000  
75%        49.500000  185.000000           3.000000    0.500000  
max       194.000000  577.000000          71.000000    1.000000

In [46]:
quality.PoorCare.value_counts()

0    98
1    33
Name: PoorCare, dtype: int64

In [48]:
X= quality.iloc[:,0:13] #it excludes 13th wala (leaving poor care that is dependent variables)( hence X has independent columns)

In [49]:
X.head()

MemberID  InpatientDays  ERVisits  OfficeVisits  Narcotics  \
0         1              0         0            18          1   
1         2              1         1             6          1   
2         3              0         0             5          3   
3         4              0         1            19          0   
4         5              8         2            19          3   

   DaysSinceLastERVisit  Pain  TotalVisits  ProviderCount  MedicalClaims  \
0                 731.0    10           18             21             93   
1                 411.0     0            8             27             19   
2                 731.0    10            5             16             27   
3                 158.0    34           20             14             59   
4                 449.0    10           29             24             51   

   ClaimLines  StartedOnCombination  AcuteDrugGapSmall  
0         222                 False                  0  
1         115                 False                  1  
2         148                 False                  5  
3         242                 False                  0  
4         204                 False                  0

In [50]:
y=quality["PoorCare"]

In [51]:
#jb hum linear regression kr re the tb jo model we didn't needed to specify x and y

In [52]:
#in logistic regression we have specify x and y

In [53]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=88,stratify=y)

In [54]:
#stratify se it maintains the same ratio of poor and good care as in train data

In [56]:
X_train.shape

(91, 13)

In [57]:
y_train.shape

(91,)

In [58]:
#91, means 91 rows , vertical list

In [59]:
X_test.shape

(40, 13)

In [60]:
y_test.shape

(40,)

In [61]:
# 40+91= 131------ total values

In [62]:
y_train.value_counts()

0    68
1    23
Name: PoorCare, dtype: int64

In [63]:
y.value_counts()

0    98
1    33
Name: PoorCare, dtype: int64

In [64]:
#hence as the ratio of good to poor is almost 3:1 in y and ytrain and ytest

In [65]:
#this is use of stratify

In [66]:
from sklearn.linear_model import LogisticRegression


In [67]:
model1= LogisticRegression()

In [68]:
model1.fit(X_train[["Narcotics","OfficeVisits"]],y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [69]:
model1.coef_

array([[ 0.10802942, -0.01197402]])

In [70]:
model1.score(X_train[["Narcotics","OfficeVisits"]],y_train)

0.8241758241758241

In [73]:
model1.score(X_test[["Narcotics","OfficeVisits"]],y_test)

0.8

In [74]:
pred_train=model1.predict(X_train[["Narcotics","OfficeVisits"]])

In [75]:
pred_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0], dtype=int64)

In [76]:
pred_train.shape

(91,)

In [77]:
len(pred_train)

91

In [78]:
pred_train_proba=model1.predict_proba(X_train[["Narcotics","OfficeVisits"]])

In [79]:
pred_train_proba

array([[0.81612454, 0.18387546],
       [0.83341812, 0.16658188],
       [0.84784713, 0.15215287],
       [0.80878721, 0.19121279],
       [0.67558948, 0.32441052],
       [0.76462294, 0.23537706],
       [0.40549024, 0.59450976],
       [0.83006676, 0.16993324],
       [0.79931452, 0.20068548],
       [0.77941757, 0.22058243],
       [0.81969114, 0.18030886],
       [0.84629601, 0.15370399],
       [0.81969114, 0.18030886],
       [0.7163064 , 0.2836936 ],
       [0.83507387, 0.16492613],
       [0.82666199, 0.17333801],
       [0.81250354, 0.18749646],
       [0.82320354, 0.17679646],
       [0.85242349, 0.14757651],
       [0.82320354, 0.17679646],
       [0.80688756, 0.19311244],
       [0.82320354, 0.17679646],
       [0.81250354, 0.18749646],
       [0.84149474, 0.15850526],
       [0.77941757, 0.22058243],
       [0.8249395 , 0.1750605 ],
       [0.81969114, 0.18030886],
       [0.25148895, 0.74851105],
       [0.12661367, 0.87338633],
       [0.8214541 , 0.1785459 ],
       [0.

In [80]:
#it gives 2 columns -----1st is good care prediction, 2nd is poor care

In [81]:
#odds in favour had p(y=0)/p(y=1)
#hence close to 1 means good care

In [83]:
pred_train_proba[:,0] #gives 1st column------good care cases

array([0.81612454, 0.83341812, 0.84784713, 0.80878721, 0.67558948,
       0.76462294, 0.40549024, 0.83006676, 0.79931452, 0.77941757,
       0.81969114, 0.84629601, 0.81969114, 0.7163064 , 0.83507387,
       0.82666199, 0.81250354, 0.82320354, 0.85242349, 0.82320354,
       0.80688756, 0.82320354, 0.81250354, 0.84149474, 0.77941757,
       0.8249395 , 0.81969114, 0.25148895, 0.12661367, 0.8214541 ,
       0.82662427, 0.8788136 , 0.83507387, 0.81787542, 0.7874978 ,
       0.80312853, 0.78553147, 0.6730176 , 0.77941757, 0.79353338,
       0.76462294, 0.80878721, 0.74915538, 0.82320354, 0.83503761,
       0.82490147, 0.83834571, 0.79927229, 0.8214541 , 0.76462294,
       0.14197323, 0.83174909, 0.76890564, 0.26759308, 0.76677113,
       0.83006676, 0.82490147, 0.81600599, 0.81242331, 0.81063216,
       0.79152124, 0.03858226, 0.26759308, 0.8249395 , 0.32248231,
       0.82833363, 0.7624611 , 0.83341812, 0.79152124, 0.81787542,
       0.8249395 , 0.81787542, 0.82833363, 0.81969114, 0.00999

In [84]:
pred_train_proba[:,1] #gives 2nd column------poor care 

array([0.18387546, 0.16658188, 0.15215287, 0.19121279, 0.32441052,
       0.23537706, 0.59450976, 0.16993324, 0.20068548, 0.22058243,
       0.18030886, 0.15370399, 0.18030886, 0.2836936 , 0.16492613,
       0.17333801, 0.18749646, 0.17679646, 0.14757651, 0.17679646,
       0.19311244, 0.17679646, 0.18749646, 0.15850526, 0.22058243,
       0.1750605 , 0.18030886, 0.74851105, 0.87338633, 0.1785459 ,
       0.17337573, 0.1211864 , 0.16492613, 0.18212458, 0.2125022 ,
       0.19687147, 0.21446853, 0.3269824 , 0.22058243, 0.20646662,
       0.23537706, 0.19121279, 0.25084462, 0.17679646, 0.16496239,
       0.17509853, 0.16165429, 0.20072771, 0.1785459 , 0.23537706,
       0.85802677, 0.16825091, 0.23109436, 0.73240692, 0.23322887,
       0.16993324, 0.17509853, 0.18399401, 0.18757669, 0.18936784,
       0.20847876, 0.96141774, 0.73240692, 0.1750605 , 0.67751769,
       0.17166637, 0.2375389 , 0.16658188, 0.20847876, 0.18212458,
       0.1750605 , 0.18212458, 0.17166637, 0.18030886, 0.99000

In [85]:
pred_test=model1.predict(X_test[["Narcotics","OfficeVisits"]])

In [86]:
pred_test #it shows only 2 data in array had poor care

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [87]:
pred_test_prob=model1.predict_proba(X_test[["Narcotics","OfficeVisits"]])

In [88]:
pred_test_prob

array([[0.78350729, 0.21649271],
       [0.8553456 , 0.1446544 ],
       [0.80692858, 0.19307142],
       [0.8214541 , 0.1785459 ],
       [0.8214541 , 0.1785459 ],
       [0.7731797 , 0.2268203 ],
       [0.7934471 , 0.2065529 ],
       [0.80878721, 0.19121279],
       [0.81787542, 0.18212458],
       [0.8249395 , 0.1750605 ],
       [0.85091082, 0.14908918],
       [0.79742941, 0.20257059],
       [0.79548829, 0.20451171],
       [0.76462294, 0.23537706],
       [0.80882792, 0.19117208],
       [0.88008306, 0.11991694],
       [0.39679779, 0.60320221],
       [0.81246343, 0.18753657],
       [0.07367798, 0.92632202],
       [0.57785125, 0.42214875],
       [0.83996189, 0.16003811],
       [0.79540261, 0.20459739],
       [0.84315498, 0.15684502],
       [0.67558948, 0.32441052],
       [0.73302628, 0.26697372],
       [0.81600599, 0.18399401],
       [0.81246343, 0.18753657],
       [0.80882792, 0.19117208],
       [0.84156496, 0.15843504],
       [0.82662427, 0.17337573],
       [0.

In [89]:
from sklearn.metrics import accuracy_score,auc,confusion_matrix,precision_score,recall_score,roc_curve

In [90]:
accuracy_score(y_train,pred_train)

0.8241758241758241

In [91]:
accuracy_score(y_test,pred_test)

0.8

In [92]:
#tomorrow will continue with confusion matrix