In [3]:
#a[0,:] for first row print
import numpy as np
a=np.array([[1,2,3],[2,5,7],[3,6,9]])
print(a[0,:])

[1 2 3]


In [4]:
print("item column 1 onwards are")
print(a[:,1:])

item column 1 onwards are
[[2 3]
 [5 7]
 [6 9]]


In [5]:
a[0,:]=0   #to make first row 0
print(a)

[[0 0 0]
 [2 5 7]
 [3 6 9]]


In [6]:
#to fetch data above 5
for i in range(3):
    for j in range(3):
        if(a[i,j]>5):
            print(a[i,j])

7
6
9


In [7]:
#with boolean indexing
f=a>5
print(f)

[[False False False]
 [False False  True]
 [False  True  True]]


In [8]:
print(a[f])

[7 6 9]


In [10]:
#to print all even numbers
g=(a%2==0)
print(g)

[[ True  True  True]
 [ True False False]
 [False  True False]]


In [11]:
print(a[g])

[0 0 0 2 6]


In [14]:
x=a.reshape(9,1)
print(x)

[[0]
 [0]
 [0]
 [2]
 [5]
 [7]
 [3]
 [6]
 [9]]


In [20]:
""""y=np.sum(a)
avg=y/9
print(avg)"""
y=np.mean(a)
print(y)

3.55555555556


In [17]:
z=x>avg
print(x[z])

[5 7 6 9]


In [19]:
print(len(x[z]))

4


In [21]:
print(x-avg)

[[-3.55555556]
 [-3.55555556]
 [-3.55555556]
 [-1.55555556]
 [ 1.44444444]
 [ 3.44444444]
 [-0.55555556]
 [ 2.44444444]
 [ 5.44444444]]


# Python